pipeline {
    agent none
    stages {

        stage ("Static code analysis"){
	    agent {
                label "master"
            }
            steps {
	            sh "/usr/local/sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner -Dsonar.login=admin -Dsonar.password=admin -Dsonar.projectVersion=${BUILD_NUMBER} -Dsonar.branch=master -Dsonar.projectKey=test -Dsonar.sources=app/ -Dsonar.exclusions=app/vendor/**"
            }
        }

        stage ("Prepare the docker app image"){
            agent {
                label "master"
            }
            steps {
                sh "docker run --rm -p 80:80 --volume ${WORKSPACE}/app:/app composer install"
                sh "${WORKSPACE}/app/docker/build.sh summalabs ${BUILD_NUMBER}"
            }
        }

        stage ("Run tests in Test Server") {

            parallel {

                stage ("Run unit tests"){
                    agent {
                        label "master"
                    }
                    steps {
                        sh "ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/id_rsa vagrant@10.10.0.11 docker run --rm summalabs/termica:${BUILD_NUMBER} php vendor/bin/codecept run unit"
                    }
                }

                stage ("Run Component tests"){
                    agent {
                        label "master"
                    }
                    steps {
                        sh "ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/id_rsa vagrant@10.10.0.11 docker run --rm summalabs/termica:${BUILD_NUMBER} php vendor/bin/codecept run functional"
                    }
                }
            }
        }

        stage ("Run E2E in Staging server"){
            agent {
                label "master"
            }
            steps {
                sh "ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/id_rsa vagrant@10.10.0.12 docker run -d --rm -p 80:80 --name termica_e2e summalabs/termica:${BUILD_NUMBER}"
                sh "sleep 5s"
                sh "ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/id_rsa vagrant@10.10.0.12 docker exec termica_e2e php vendor/bin/codecept run acceptance"
                sh "ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/id_rsa vagrant@10.10.0.12 docker stop termica_e2e"
            }
        }
    }
    post {
        always {
            node("master") {
                sh "docker rmi summalabs/termica:${BUILD_NUMBER}"
            }
        }
    }
}
